version: '3.1'

services:

  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: laravel
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: dnw-next
    ports:
      - "3407:3306"
  db_test:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: laravel
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: dnw-next
    ports:
      - "3408:3306"
